### ISSUE TITLE
Update to nginx 1.7.11

### ISSUE THREAD

**Issue by jfjallid** [lerenn/docker-images#2]
Hello!

Any chance that you could update this image to use nginx version >= 1.7.11? 
I'm quite fond of this image and have been using it for a while but have now run into a situation where I would like to use some directives introduced in nginx version 1.7.11.

**Comment by lerenn** [comment]
Hello ! No problem, if it's in the repositories, I just launched the jobs to recompile the images.
If it's not, feel free to make a pull request to include this version ;)
